apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: web-split
  namespace: emojivoto
spec:
  service: web-svc
  backends:
    - service: web-svc
      weight: 800m        
    - service: web-svc-canary
      weight: 200m        